config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "posts#index"
    get 'posts/new'
	get '/top' => 'root#top'
    post '/posts' => 'posts#create'
    get '/posts/:id' => 'posts#show', as: 'post'
    get '/posts' => 'posts#index'
    get '/posts/:id/edit' => 'posts#edit', as: 'edit_post'
    patch '/posts/:id' => 'posts#update', as: 'update_post'
    delete '/posts/:id' => 'posts#destroy', as: 'destroy_post'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
	attachment :image
	validates :title, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  def new
  	  @post = Post.new
  end
  def create
  	  @post = Post.new(post_params)
      #@post.save
      #redirect_to post_path(@post.id)
    if @post.save
      redirect_to @post, notice: 'titleを登録しました'
    else
      render :new
    end
  end
  def index
  	#@posts = Post.all
      @posts = Post.page(params[:page]).per(3)
  end
  def show
  	@post = Post.find(params[:id])
  end
  def edit
    @post = Post.find(params[:id])
  end
  def update
    @post = Post.find(params[:id])
    @post.update(post_params)
    redirect_to post_path(@post.id)
  end
  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end
  private
  def post_params
      params.require(:post).permit(:title, :body, :image,)
  end
end

app/controllers/root_controller.rb
class RootController < ApplicationController
	def top
		
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/root_helper.rb
module RootHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SampleApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
  <body>
  <% if user_signed_in? %>
    Logged in as <%= current_user.email %>
    <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
    <%#= link_to 'プロフィール変更', edit_user_registration_path %>
  <% else %>
    <%= link_to "新規登録", new_user_registration_path %> |
    <%= link_to "ログイン", new_user_session_path %>
  <% end %>
    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<h1>編集画面</h1>
<%= form_for(@post) do |f| %>
	<h4>タイトル</h4>
	<%= f.text_field :title %>
	<h4>本文</h4>
	<%= f.text_area :body %>
	<%= f.submit '保存' %>
<% end %>

app/views/posts/index.html.erb
<h1>投稿一覧</h1>
<% @posts.each do |post| %>
	<p>タイトル</p>
	<span>
	  <%= link_to post.title, "/posts/#{post.id}" %>
	</span>
	<p>画像</p>
	<%= attachment_image_tag post, :image, :fill, 100, 100, format: 'jpeg' %>
	<% end %>
	<div>
   <%#= link_to 'ログアウト', destroy_user_session_path %>

　　</div>
<%= paginate @posts %>

app/views/posts/new.html.erb
<h1>新規投稿</h1>

<%= form_for(@post) do |f| %>

   <h4>タイトル</h4>
   <%= f.text_field :title %>

   <h4>本文</h4>
   <%= f.text_area :body %>

   <h4>画像</h4>
   <%= f.attachment_field :image %>

   <%= f.submit '投稿' %>

   <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= @post.errors.count %>件のエラーが発生しました。</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
   <% end %>

<% end %>

app/views/posts/show.html.erb
<h2>タイトル</h2>
<%= @post.title %>
<h2>本文</h2>
<%= @post.body %>
<h2>画像</h2>
<%= attachment_image_tag @post, :image, :fill, 300, 300, format: 'jpeg' %>
<%= link_to "編集", edit_post_path(@post.id) %>
<%= link_to "削除", destroy_post_path(@post.id), method: :delete,"data-conferm" => "本当に削除しますか？" %>

app/views/root/top.html.erb
<h1>ここはtopページです</h1>